######################## default configuration ####################
baseURL = "https://618d31465982e800ba925465--kind-wescoff-e17f56.netlify.app/"
title = 'Pedreiro Programador'
theme = "twenty-twenty-hugo"
languageName = "PT-BR"
languageCode = "pt-br"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here
# google analytics
googleAnalytics = "" # example : UA-123-45



############################## Output ###############################
[outputs]
home = ["HTML", "RSS", "JSON"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
author = "author"

############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "/"
weight = 1


# only desktop menu
#[[menu.desktop]]
#name = "Contact"
#URL = "contact"
#weight = 1
#enable = false

#################### default parameters ################################
[params]
# Meta data
#description = "This is meta description"
#author = "Themefisher"

# favicon
[params.favicon]
favicon = "images/favicon.png"

# cookies
[params.cookies]
enable = true
expire_days = 2

# banner
[params.banner]
heading = "Começado pelo primeiro tijolo..."
image = "/images/stock-photo-164998937.jpeg"

# blog
# [params.blog]
# heading = "The premier destination for modern art in Northern Sweden. Open from 10 AM to 6 PM every day during the summer months."

# call to action
[params.call_to_action]
enable = false
title = "Contact us for more information."
content = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis"
button_label = "Contact Us"
button_url = "contact"

# gallery
[params.gallery]
enable = false

[[params.gallery.gallery_item ]]
image = "images/2020-square-2.png"

[[params.gallery.gallery_item ]]
image = "images/2020-square-1.png"


# footer
#[params.footer]
#enable = false
#title = "Sobre"
#content = "This may be a good place to introduce yourself and your site or include some credits."
#address = "123 Main Street <br> New York, NY 10001"
#hours = "Monday–Friday: 9:00AM–5:00PM <br> Saturday & Sunday: 11:00AM–3:00PM"

############################# social site ########################
[params.social]
#facebook = "#"
#instagram = "#"
email = "pedreiroprogramador@gmail.com"
#linkedin = "#"
